- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
- V2AdminStreamInfo's isExternal "deprecated" attribute is not valid : let's only mention "deprecated" inside the description
- UserInfo definition is not used anywhere : removed
- UserDetail definition moved to non-deprecated definitions because it is used in the non-deprecated /v1/admin/user/find endpoint
> PLAT-5321 Fix r51 YAML files

- CONTRIBUTING.md
- README.md
@brooklynrob I saw your email about CLAs via the FINOS mailing list. I've made a few small changes to the contributing text (FINOS OR looked like some sort of new organization or group), and moved the text to a CONTRIBUTING file, which gives greater visibility as per the [GitHub guidelines](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors).
> Moved CLA text to a contributing file and minor edit

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
The `keyManagerToken` attribute was always required, as it is not OBO-enabled. Currently the application returns a 400 Bad Request status when the attribute is not provided.
> Fix: v1/message/{id} endpoint definition to set keyManagerToken as a required param

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
(Reference PR: https://github.com/symphonyoss/symphony-api-spec/pull/39)
The keyManagerToken attribute was always required, as it is not OBO-enabled. Currently the application returns a 400 Bad Request status when the attribute is not provided.
> (rc-current-r55) Fix: v1/message/{id} endpoint swagger definition to mark keyManagerToken as a required param

- agent/agent-api-public-deprecated.yaml
Fixes https://github.com/symphonyoss/symphony-api-spec/issues/46
> Adding missing attribute 'consumes: application/json' to v1/message/search endpoint

- authenticator/authenticator-api-public.yaml
Renamed tags in authenticator api to avoid generated classes to be overwritten.
Having same tag "Authentication" in both https://github.com/symphonyoss/symphony-api-spec/blob/master/authenticator/authenticator-api-public.yaml and https://github.com/symphonyoss/symphony-api-spec/blob/master/login/login-api-public.yaml resulted in one single class AuthenticationApi reflecting only login-api-public.yaml
This is needed in scope of APP-2845
> Renamed tags in authenticator api to clashes across several files

- authenticator/authenticator-api-public-deprecated.yaml
Apply change also inside authenticator-api-public-deprecated.yaml file
> Renamed tags in authenticator api to avoid generated classes to be overwritten

- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
[PLAT-10435](https://perzoinc.atlassian.net/browse/PLAT-10435) : BDK2.0 Java - Change tag name for /roles/list in Swagger spec
The pod-api-public and pod-api-public-deprecated were mentioning "System" as a tag for "/roles/list" endpoint. This tag being duplicated in agent public api, it is overwritten in symphony-api-client and only agent's system api class is generated.
In this PR, the tag for "/roles/list" is changed to match the same as "/roles/add" and "/roles/remove".
> PLAT-10435 - Change tag name for /roles/list in Swagger spec

- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
[PLAT-10435](https://perzoinc.atlassian.net/browse/PLAT-10435) : BDK2.0 Java - Change tag name for /roles/list in Swagger spec
The pod-api-public and pod-api-public-deprecated were mentioning "System" as a tag for "/roles/list" endpoint. This tag being duplicated in agent public api, it is overwritten in symphony-api-client and only agent's system api class is generated.
In this PR, the tag for "/roles/list" is changed to match the same as "/roles/add" and "/roles/remove".
> PLAT-10435 - (backport) Change tag name for /roles/list in Swagger spec

- README.md
This pull request adds the FINOS `Active` project badge to the project's [README.md](https://github.com/symphonyoss/symphony-api-spec/blob/master/README.md) to reflect the `Active` status of the project within the FINOS foundation.
[![FINOS - Active](https://cdn.jsdelivr.net/gh/finos/contrib-toolbox@master/images/badge-active.svg)](https://finosfoundation.atlassian.net/wiki/display/FINOS/Active)
```
[![FINOS - Active](https://cdn.jsdelivr.net/gh/finos/contrib-toolbox@master/images/badge-active.svg)](https://finosfoundation.atlassian.net/wiki/display/FINOS/Active)
```
> Add FINOS Active Badge to Symphony API Spec project README.md

- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
**PLAT-10436 :** Change roleDetails definition to support string without Long format constraint.
RoleDetails was defined as a string in Long format which prevent us to create roles as defined in [Roles Object documentation](https://developers.symphony.com/restapi/reference#roles-object). This is changed to support Strings without Long format constraint.
> Backport PLAT-10436 : Change roleDetails definition to support string ids without Long format constraint

- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
**PLAT-10436 :** Change roleDetails definition to support string without Long format constraint.
RoleDetails was defined as a string in Long format which prevent us to create roles as defined in [Roles Object documentation](https://developers.symphony.com/restapi/reference#roles-object). This is changed to support Strings without Long format constraint.
> Backport PLAT-10436 : Change roleDetails definition to support string ids without Long format constraint 

- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
The role was set as a string with long format whereas it is just a
string. This is preventing clients using generated code to properly
work.
Change done in SBE, backporting it here for next release.
Related to https://github.com/SymphonyOSF/SBE/pull/21998
> PLAT-10651: Wrong format for UserFilter.role field in specification

- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
Field Pagination.cursors.after was not aligned with actual behaviour where it is optional (field is not sent back when we are at the last page of results).
This was causing the Python BDK2.0 to fail when receiving a response without the after field.
Opened https://github.com/SymphonyOSF/SBE/pull/22009
> PLAT-10688: Made Pagination.cursors.after optional

- pod/pod-api-public.yaml
The sku property is not required in a default product but only in premium ones.
In the case of a premium product, the verification of this property is Done in AppUtil.java so it shouldn't be a breaking change.
> PLAT-10555 - Making the product sku property optional

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
This is used to support running multiple instances of a bot.
This is added manually now so we can start using it before a release of the agent/specs.
> PLAT-10410: Add tag parameter for DF2 Agent's API

- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
When trying to generate python BDK code, we get an error related to a non found reference. It seems the UserAppEntitlementsPatchList didn't have the full reference path.
> PLAT-10714 Fix UserAppEntitlementsPatchList reference paths

- authenticator/authenticator-api-public-deprecated.yaml
- authenticator/authenticator-api-public.yaml
- login/login-api-public.yaml
We would like to start using the common jwt/authorization token in the public APIs, to do so we need our BDKs to be able to retrieve this token during the authentication process.
To avoid making extra calls to the idm/tokens endpoint a new field called authorizationToken is been added in the payload for both login/pubkey/authenticate (used in RSA authentication) and sessionauth/v1/authenticate (used for Certificate authentication).
The authorization token will have the following format "Bearer authTokenValue" so that can be directly used as it is in the Authorization header for any subsequential calls to our public APIs.
For now this token will be introduced only for users authentication and not for apps which will be handled in the future.
> PLAT-11563 Adding authToken field in authentication endpoints

- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
This PR is related to [PLAT-11717](https://perzoinc.atlassian.net/browse/PLAT-11717)
In this commit, we updated pod-api-public to add suspension fields (suspended, suspensionUntil, suspensionReason) to UserSystemInfo and UserStatus objects that are used in user endpoints response/parameters.
> PLAT-11717: Add suspension info to user status endpoint

- authenticator/authenticator-api-public-deprecated.yaml
- authenticator/authenticator-api-public.yaml
Start deprecation process for the Apps authentication endpoints that are using certificates.
- `/sessionauth/v1/authenticate/extensionApp` should be replaced by `/login/v1/pubkey/app/authenticate/extensionApp`
- `/sessionauth/v1/app/authenticate` should be replaced by `/login/v1/pubkey/app/authenticate`
- `/sessionauth/v1/app/user/:uid/authenticate`  should be replaced by `/login/v1/app/user/:uid/authenticate`
- `/sessionauth/v1/app/username/:username/authenticate` should be replaced by `/login/v1/app/username/:username/authenticate`
> Flag the Apps Auth endpoints using Certificates as Deprecated

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
Datafeed v1 will be soon fully replaced by Datafeed v2. 
V4Datafeed APIs (using DFv1) are being deprecated in this PR in favor of V5 API (using DFv2).
Two endpoint have been deprecated :
- POST `/agent/v4/datafeed/create`
- GET `/agent/v4/datafeed/{id}/read`
> Deprecate V4 Datafeed API

- agent/agent-api-public-deprecated.yaml
While trying to generate the code in the BDK deprecated attribute was throwing the following error:
`-attribute definitions.V1HealthCheckResponse.deprecated is unexpected`
Also the header what wrong formatted.
> Fixing some errors/warnings in the specs definition

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
In Agent api specs, pagination's cursors before/after should be optional
> Fix pagination cursors specs

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
- login/login-api-public.yaml
- pod/pod-api-public-deprecated.yaml
- pod/pod-api-public.yaml
To decouple SBE/Agent releases, start adding information specific
information in the specification.
x-since is not used by any tool but is here as a meta information that
could potentially be used in the future. Therefore we also set this as
part of the description.
Backport this approach to changes from 20.14 version.
> AGNT-9: Use master branch only

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
As we are using master branch only, just drop it and use the next
version of the Agent instead. Once we start putting new features in the
spec we can increment this number manually too.
Upon a release when we synchronize the internal specs with those being
public we will put anyway the released version of the Agent or SBE.
> AGNT-9: Drop snapshot in Swagger spec version

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
Those events are not yet handled by the Agent so avoid mentionning them
in the OpenAPI specification.
> Remove unsupported Datahose events from documentation

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
- postman/Symphony_REST_APIs.postman_collection.json
The `/v5/events/read` endpoint (used mostly for datahose feeds) is updated to support the Real-time events as filters (MESSAGE SENT, ROOMCREATED, ROOMUPDATED, etc.) as defined in https://docs.developers.symphony.com/building-bots-on-symphony/datafeed/real-time-events.
Added Postman example for this endpoint
> AGNT-53: support Real-time Events in datahose

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
- agent/swagger2/agent-api-public-deprecated.yaml
- agent/swagger2/agent-api-public.yaml
Goal of this commit is to migrate Agent APIs to start using OpenAPI 3 instead of swagger 2.
Swagger 2 version is still available to maintain compatibility with existing systems that are using the specs to generate code but it will not be updated with the new coming features. Only OpenApi 3 version will be kept up to date with new implementations from now on.
> Migrating agent APIs to OpenApi 3

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
The agent is not setting the createdAt field, is not something we receive from DFv2. In this commit we are going to tag it as deprecated, since it cannot be removed now without breaking backward compatibility.
> Tagging createdAt field as deprecated in V5Datafeed

- agent/swagger2/agent-api-public-deprecated.yaml
- agent/swagger2/agent-api-public.yaml
- authenticator/authenticator-api-public-deprecated.yaml
- authenticator/authenticator-api-public.yaml
- login/login-api-public.yaml
Tagging AuthorizationToken field as still in beta, therefore not to be used for now.
AuthorizationToken is a new field returned in the response payload of the following endpoints:
- [Session Authenticate](https://symphony.readme.io/restapi/reference/rsa-session-authenticate) 
- [Session Authenticate (Cert)](https://symphony.readme.io/restapi/reference/session-authenticate)
> Tag AuthorizationToken as beta

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
In last update,  array fields have been made as required in specs, maybe in order to avoid NPs. This causes issue in code generation in BDK Python. 
This PR is just a test to check if setting a default empty array value for those fields could be a compromise.
> Set default empty array instead of making the field as required for non-required fields

- agent/agent-api-public.yaml
Added new field `recipientTenantIds` in V4Stream, to expose the involved tenants of the conversations, in datafeed / datahose real-time messages.
> AGNT-452: add recipientTenantIds in V4Stream for real time feed

- agent/agent-api-public-deprecated.yaml
- agent/agent-api-public.yaml
Starting from Agent 24.12, kmToken will be optional, this PR updates the swagger definition to take this into account
> AGNT-586 Make kmToken optional for agent calls in preparation of skd
