pod/pod-api-public-deprecated.yaml
pod/pod-api-public.yaml

Changed String model/reference name to SymString

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml

(cherry picked from commit 6f1aaaf)
@dnsymphony please review

PLAT-4119 Remove x-www-form-urlencoded from V4 message spec

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml
authenticator/authenticator-api-public-deprecated.yaml
authenticator/authenticator-api-public.yaml
pod/pod-api-public-deprecated.yaml
pod/pod-api-public.yaml

rc-current-r49

---

agent/agent-api-public.yaml

PLAT-8550 Added sid to V4Message

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml
authenticator/authenticator-api-public-deprecated.yaml
authenticator/authenticator-api-public.yaml
login/login-api-public.yaml
pod/pod-api-public-deprecated.yaml
pod/pod-api-public.yaml
pom.xml

Global update of our APIs specifications for `R58` (`20.4.1`) release.

Specs updated for r58 (20.4.1)

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml
authenticator/authenticator-api-public-deprecated.yaml
authenticator/authenticator-api-public.yaml
login/login-api-public.yaml
pod/pod-api-public-deprecated.yaml
pod/pod-api-public.yaml
pom.xml

Symphony public APIs specification update for R59 (20.5.1)
Global update of our APIs specifications for R59 (20.5.1) release.

Specs updated for r59 (20.5.1)

---

login/login-api-public.yaml

Added swagger specifications for a new public endpoint login/idm/tokens used to retrieve the commonJWT from a sessionToken

PLAT-11121 Adding new login endpoint for the commonJWT

---

postman/Develop2.postman_environment.json
postman/Symphony_REST_APIs.postman_collection.json

Addition of new endpoint PATCH /pod/v1/admin/user/:uid/app/entitlement/list for partial update of user entitlements

PLAT-10661

---

postman/Symphony_REST_APIs.postman_collection.json

Add Common JWT endpoint in Postman

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml
authenticator/authenticator-api-public-deprecated.yaml
authenticator/authenticator-api-public.yaml
login/login-api-public.yaml
pod/pod-api-public-deprecated.yaml
pod/pod-api-public.yaml

This is an auto swagger specifications update from Jenkins

Jenkins Swagger specifications update 20.14.0-SNAPSHOT

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml
authenticator/authenticator-api-public-deprecated.yaml
authenticator/authenticator-api-public.yaml
login/login-api-public.yaml
pod/pod-api-public-deprecated.yaml
pod/pod-api-public.yaml
pom.xml

This is an auto swagger specifications update from Jenkins

Jenkins Swagger specifications update 20.14.0

---

README.md
community-connect/community-connect-public-api.yaml

Hello @symphony-mariacristina @justinesymphony @jspasquali , could you please review my PR regarding Community Connect public Api, I don't have the right to add reviewers

Add Community Connect swagger documentation + update README.md accordingly

---

pod/pod-api-public.yaml

DLP-7850: Filtering inbound attachment by extension

---

pod/pod-api-public.yaml

Added examples to the swagger specs of the pod public apis.

Pod swagger examples

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml

Improved datahose API documentation and aligned Agent spec

Improve datahose description and example

---

pod/pod-api-public.yaml

Fix Gitbook empty server path

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml

* Adding `tier` parameter for message search
* Adding support of generic system events

AGNT-546: add search tier parameter

---

pod/pod-api-public.yaml

Add spec for user management endpoints :
- /v1/users/{uid}/sessions/{sid}/logout
- /v1/users/{uid}/sessions/logout
- /v1/users/{uid}/sessions

SEC-6977   DOC - Add user session management documentation in public finos repo 

---

pod/pod-api-public.yaml

Add missing session definition.

SEC-7054   [DOC] Fix open api spec for session management on Finos

---

agent/agent-api-public-deprecated.yaml
agent/agent-api-public.yaml
agent/swagger2/agent-api-public-deprecated.yaml
agent/swagger2/agent-api-public.yaml
pod/pod-api-public.yaml

This patch allows generating the [Python](https://github.com/finos/symphony-bdk-python) code.

Bring Agent API patch for Python generation back to master
